# Generated by Django 5.0.2 on 2024-02-12 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('metahotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBindingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_history', to='hotels.hotel')),
                ('meta_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metahotels.metahotel')),
            ],
        ),
    ]
