# Generated by Django 5.0.2 on 2024-02-11 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('metahotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='meta_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='metahotels.metahotel'),
        ),
        migrations.DeleteModel(
            name='MetaHotel',
        ),
    ]
